name: generate-documentation
run-name: Generate Documentation for all JS files in source
on: [push]

jobs:
  create-docs:
    runs-on: ubuntu-latest

    permissions:
      # Lets this job push the docs to the repository
      contents: read
      pages: write

    strategy:
      matrix:
        nodeversion: [16]
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          path: "src"
          persist-credentials: false
      - name: Checkout documentation repo
        uses: actions/checkout@v3
        with:
          repository: "CSE-112-Team-7/CSE-112-Team-7-Docs"
          path: "dest"
          persist-credentials: true
          token: ${{ secrets.DOCS_ACCESS }}
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodeversion }}
      - name: Delete old Docs
        run: rm -rf ./dest/docs
      - name: Create documentation for pages
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./src/source/pages
          recurse: true
          output_dir: ./dest/docs/pages
      - name: Create documentation for backend
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./src/backend
          recurse: true
          output_dir: ./dest/docs/backend

      - name: Push documentation to docs repository
        run: |
          cd dest
          git config --global user.email "gitaction@gitaction.com"
          git config --global user.name "Documentation Action"
          git add docs
          git commit -m "Updating docs"
          git push
