name: Continuous Integration Tests

on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        nodeversion: [16]
        jestversion: [29.7.0]
        jestpuppeteerversion: [10.0.1]
        puppeteerversion: [22.10.0]
        httpserverversion: [14.1.1]

    steps:
      - uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodeversion }}
      - name: Install JEST
        run: npm install jest@${{ matrix.jestversion }} jest-puppeteer@${{ matrix.jestpuppeteerversion }} puppeteer@${{ matrix.puppeteerversion }} http-server@${{ matrix.httpserverversion }}; cd backend; npm install;
      - name: Host Server
        run: cd backend; node index.mjs
      - name: Run tests
        run: npm run test
